### ISSUE TITLE
Compile in memory

### ISSUE THREAD

**Issue by skostic9242** [MeadowSuite/SolcNet#2]
Hi,

is there a way to compile one or more contracts in memory instead of specifying path to them? 

Cheers

**Comment by skostic9242** [comment]
Hi,

tnx for response. :)

But i don't understand, is it possible to do it via SolcNet or no? Do you have some example of this InputDescription object? 

Cheers

**Comment by zone117x** [comment]
I just added a unit test demonstrating how to do this:
https://github.com/MeadowSuite/SolcNet/blob/3d0f8ea5faf22c2c7c65c5a6324c964d917a3283/SolcNet.Test/BindingTests.cs#L107

**Comment by skostic9242** [comment]
Thank you again

**Comment by skostic9242** [comment]
Actually, compiling doesn't throw any errors, but Abi and Evm and ByteCode etc in output is null...

**Comment by zone117x** [comment]
You will want to read the solc docs linked to above since this is just a .NET wrapper around solc. So all the inputs/outputs/behaviors will match those docs.

You need to specify `OutputType`.
